# Generated by Django 3.0.5 on 2020-04-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sidebar',
            old_name='desplay_type',
            new_name='display_type',
        ),
    ]
